from rsf.book import *

papers = ['hw%d' % x for x in range(1,7)]

Book(title='\\Large{GEO384W} \\\\ Seismic Imaging  \\\\ Homework Assignments',
     author='Sergey Fomel',
     chapters=papers)

End(options='book',use='hyperref,listings')
