from rsf.book import *

papers = ['hw%d' % x for x in range(1,7)]

Book(title='\\Large{GEO391} \\\\ Multidimensional Data Analysis in Geosciences \\\\ Homework Assignments',
     author='Sergey Fomel',
     chapters=papers)

End(options='book',use='hyperref,listings,newalg')
